(* compiler.ml*)
open Pervasives
open Lexer
open Parser

let arg_list =
  [
  ("-parse",
  Arg.String (fun str -> print_endline (Display.string_of_exp (Parser.prog token (Lexing.from_channel (open_in str))))),
  "Prints the abstract syntax tree generated by the parser");
  ]

let usage_msg =
    "Usage: compiler [flag] [filename.arith]\nAvailable flags:"

let main () =
  Arg.parse
  (Arg.align arg_list)
  (fun x -> (open_in x
    |> Lexing.from_channel
    |> prog token
    |> Lang.interpret
    |> Lang.string_of_interpreted
    |> print_endline))
  usage_msg

let _ = if !Sys.interactive then () else main ()
